version: "3.9"

services:
  front_nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    depends_on:
      - front_app
  front_app:
    build:
      context: .
      args:
        - NODE_ENV=production
    restart: always
